name: Tag and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  tag-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # щоб бачити всі теги

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Extract version from last tag and increment
        id: get-version
        run: |
          latest=$(git tag --sort=-v:refname | grep '^v' | head -n1)
          echo "Latest tag: $latest"
          if [[ -z "$latest" ]]; then
            major=1; minor=0; patch=0
          else
            base=$(echo "$latest" | sed 's/^v//')
            major=$(echo "$base" | cut -d. -f1)
            minor=$(echo "$base" | cut -d. -f2)
            patch=$(echo "$base" | cut -d. -f3)
          fi

          COMMIT_MSG=$(git log -1 --pretty=%B)

          if echo "$COMMIT_MSG" | grep -iq "#major"; then
            major=$((major + 1))
            minor=0
            patch=0
          elif echo "$COMMIT_MSG" | grep -iq "#minor"; then
            minor=$((minor + 1))
            patch=0
          elif echo "$COMMIT_MSG" | grep -iq "#patch"; then
            patch=$((patch + 1))
          else
            patch=$((patch + 1))
          fi

          version="$major.$minor.$patch"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set up Maven settings for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${GITHUB_ACTOR}</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
