name: Deploy to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set version from tag
        run: |
          VERSION="${GITHUB_REF##*/}"
          mvn versions:set -DnewVersion=${VERSION#v}
          mvn versions:commit

      - name: Create settings.xml for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to GitHub Packages
        run: mvn deploy
