name: Deploy to GitHub Packages

on:
  workflow_run:
    workflows: [ "Version and Tag" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set version from tag
        run: |
          VERSION="${GITHUB_REF##*/}"
          mvn versions:set -DnewVersion=${VERSION#v}
          mvn versions:commit

      - name: Show artifact details
        run: |
          VERSION="${GITHUB_REF##*/}"
          PARSED_VERSION="${VERSION#v}"

          echo "GITHUB_REF: $GITHUB_REF"
          echo "Parsed version from tag: $PARSED_VERSION"
          echo "Maven coordinates:"
          echo -n "  groupId = "; mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout
          echo -n "  artifactId = "; mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout
          echo -n "  version = "; mvn help:evaluate -Dexpression=project.version -q -DforceStdout

      - name: Create settings.xml for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to GitHub Packages
        run: mvn deploy
