name: Deploy to GitHub Packages

on:
  workflow_run:
    workflows: [ "Version and Tag" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Fetch tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "tag=$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Set version from tag
        run: |
          VERSION=${{ steps.get_tag.outputs.tag }}
          echo "Using tag version: $VERSION"
          mvn versions:set -DnewVersion=${VERSION#v}
          mvn versions:commit

      - name: Show artifact details
        run: |
          VERSION="${GITHUB_REF##*/}"
          PARSED_VERSION="${VERSION#v}"

      - name: Create settings.xml for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_PACKAGES_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy to GitHub Packages
        run: mvn deploy
