name: Version and Tag

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get last tag
        id: get_tag
        run: |
          echo "last_tag=$(git describe --tags --abbrev=0 || echo v0.0.0)" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: version
        run: |
          LAST=${{ steps.get_tag.outputs.last_tag }}
          MAJOR=$(echo $LAST | cut -d. -f1 | tr -d 'v')
          MINOR=$(echo $LAST | cut -d. -f2)
          PATCH=$(echo $LAST | cut -d. -f3)

          MSG=$(git log -1 --pretty=%B)

          if echo "$MSG" | grep -iq "#major"; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif echo "$MSG" | grep -iq "#minor"; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEXT_TAG="v$MAJOR.$MINOR.$PATCH"
          echo "next_tag=$NEXT_TAG" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: |
          git tag ${{ steps.version.outputs.next_tag }}
          git push origin ${{ steps.version.outputs.next_tag }}
